version: '3'
services:
  db:
    container_name: user-service-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: portalgen_user
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - loadbalancing

  service:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: portalgen_user
      DB_USER: mysql
      DB_PASSWORD: mysql
    deploy:
        replicas: 2
    depends_on:
      - db
    networks:
      - loadbalancing

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - service
    networks:
      - loadbalancing

volumes:
  db_data:

networks:
  loadbalancing: